modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/TagnumElite/ProjectE-Integration/issues"

[[mods]]
modId = "projecteintegration"
version = "${file.jarVersion}"
displayName = "ProjectE Integration"
updateJSONURL = "https://raw.githubusercontent.com/TagnumElite/ProjectE-Integration/1.18.x/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/projecte-integration"
# logoFile="examplemod.png"
credits = ""
authors = "TagnumElite"
description = '''
A mods that allowes ProjectE to understand the contents of recipes from other mods!
'''

[[dependencies.projecteintegration]]
modId = "projecte"
mandatory = true
versionRange = "[PE1.0.1,)"

#[[dependencies.projecteintegration]]
#modId = "compactcrafting"
#mandatory = false
#versionRange = "[1.0.0,)"

[[dependencies.projecteintegration]]
modId = "chipped"
mandatory = false
versionRange = "[2,)"

[[dependencies.projecteintegration]]
modId = "create"
mandatory = false
versionRange = "[0.5.0,)"

[[dependencies.projecteintegration]]
modId = "farmersdelight"
mandatory = false
versionRange = "[1.18.2-1.1.2,)"

[[dependencies.projecteintegration]]
modId = "pneumaticcraft"
mandatory = false
versionRange = "[1.18.2-3.3.0,)"

[[dependencies.projecteintegration]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projecteintegration]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
