modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/TagnumElite/ProjectE-Integration/issues"

[[mods]]
modId = "projecteintegration"
version = "${file.jarVersion}"
displayName = "ProjectE Integration"
updateJSONURL = "https://raw.githubusercontent.com/TagnumElite/ProjectE-Integration/1.19.x/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/projecte-integration"
# logoFile="examplemod.png"
credits = "Thanks to ProjectE team for ProjectE"
authors = "TagnumElite"
description = '''
ProjectE Integration is a mod for adding support for mapping recipes from other mods to something that ProjectE understands
and is able to convert to emc with
'''

[[dependencies.projecteintegration]]
modId = "projecte"
mandatory = true
versionRange = "[PE1.0.0B,)"

[[dependencies.projecteintegration]]
modId = "alchemistry"
mandatory = false
versionRange = "[1.19.2-2.2,)"

[[dependencies.projecteintegration]]
modId = "create"
mandatory = false
versionRange = "[0.5.1,)"

#[[dependencies.projecteintegration]]
#modId = "farmersdelight"
#mandatory = false
#versionRange = "[1.18.2-1.1.2,)"

#[[dependencies.projecteintegration]]
#modId = "pneumaticcraft"
#mandatory = false
#versionRange = "[1.18.2-3.3.0,)"

[[dependencies.projecteintegration]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projecteintegration]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
