modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/TagnumElite/ProjectE-Integration/issues"

[[mods]]
modId = "projecteintegration"
version = "${file.jarVersion}"
displayName = "ProjectE Integration"
updateJSONURL = "https://raw.githubusercontent.com/TagnumElite/ProjectE-Integration/1.16.x/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/projecte-integration"
# logoFile="examplemod.png"
authors = "TagnumElite"
description = '''
ProjectE Integration is a mod for adding support for mapping recipes from other mods to something that ProjectE understands
and is able to convert to emc with.
'''

[[dependencies.projecteintegration]]
modId = "projecte"
mandatory = true
versionRange = "[PE1.0.1B,)"

[[dependencies.projecteintegration]]
modId = "farmersdelight"
mandatory = false
versionRange = "[1.16.5-0.5,)"

#[[dependencies.projecteintegration]]
#modId = "compactcrafting"
#mandatory = false
#versionRange = "[1.0.0,)"

[[dependencies.projecteintegration]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projecteintegration]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
