# Just to let you know, this has mostly been ~stolen~ copied from https://github.com/CompactMods/CompactCrafting/blob/1.16.x/.github/workflows/tagged-release.yml
# Why? Just because I'm lazy, that's about it.
name: Latest Tag

on:
    push:
        tags:
            - v3*
    workflow_dispatch:

jobs:
    buildAndPublishCurse:
        name: Build Jars
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up JDK 1.8
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: '8'
                    cache: 'gradle'

            - uses: gradle/wrapper-validation-action@v1

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build and Publish JAR with Gradle
              run: ./gradlew build curseforge
              env:
                  GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

            - name: Upload Jars
              uses: actions/upload-artifact@v2
              with:
                  name: libs
                  path: build/libs/*.jar
    publishRelease:
        name: Make Releases
        runs-on: ubuntu-latest
        needs: [ buildAndPublishCurse ]
        steps:
            - name: Download Build Results
              uses: actions/download-artifact@v2
              with:
                  name: libs
                  path: build/libs

            - name: Get TAG
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Create GitHub Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  title: "Release ${{ env.RELEASE_VERSION }}"
                  automatic_release_tag: "latest"
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: build/libs/*.jar

    publishGithub:
        name: GitHub Packages release
        runs-on: ubuntu-latest
        needs: [ buildAndPublishCurse ]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '8'
                  cache: 'gradle'

            - uses: gradle/wrapper-validation-action@v1

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Publish package
              run: ./gradlew publish
              env:
                  GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
